<?php

namespace FrontBundle\Repository;

/**
 * FacilitateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilitateurRepository extends \Doctrine\ORM\EntityRepository
{
}
