<?php

namespace FrontBundle\Repository;

/**
 * Tag1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tag1Repository extends \Doctrine\ORM\EntityRepository
{
}
