<?php

namespace FrontBundle\Repository;

/**
 * Tag2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tag2Repository extends \Doctrine\ORM\EntityRepository
{
}
