<?php

namespace FrontBundle\Repository;

/**
 * Tag3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tag3Repository extends \Doctrine\ORM\EntityRepository
{
}
